"""empty message

Revision ID: 18427295e755
Revises: 10c494a71507
Create Date: 2025-08-04 21:23:28.332437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18427295e755'
down_revision = '10c494a71507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
