"""empty message

Revision ID: 81a54cd56fdb
Revises: c39888c5329f
Create Date: 2025-08-04 20:57:30.825851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a54cd56fdb'
down_revision = 'c39888c5329f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['following_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
